# Project Info
site_name: 'BluebirdPS'
site_description: 'Online Help for BluebirdPS PowerShell Module'
site_author: 'Dave Carroll'
site_url: 'https://bluebirdps.anovelidea.org'

# Repo Info
repo_name: 'thedavecarroll/BluebirdPS'
repo_url: 'https://github.com/thedavecarroll/BluebirdPS'

# Copyright
copyright: "Copyright &copy; 2020 Dave Carroll<br/>BluebirdPS is licensed under the <a href=https://github.com/thedavecarroll/BluebirdPS/raw/main/LICENSE>MIT license."

# Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

# Configuration
theme:
  name: material
  language: en
  icon:
    logo: fontawesome/regular/comments
  palette:
      scheme: preference
      primary: blue
      accent: indigo
  font:
      text: Roboto
      code: Roboto Mono
  features:
    - navigation.tabs

plugins:
  - search
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thedavecarroll/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thedavecarroll
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thedavecarroll/

# Navigation
nav:
  - Home: README.md
  - Getting Started:
    - How to Install: how-to-install.md
    - Pre-requisites: prerequisites.md
  - Change Log: CHANGELOG.md
  - License: LICENSE.md
  - Commands:
      - ...
